services:
  - type: web
    name: anime-recommender
    env: docker
    plan: free
    buildCommand: ""
    startCommand: python main.py
    repo: https://github.com/dpb3k/anime-recommender
    envVars:
      - key: FLASK_ENV
        value: production
